### ISSUE TITLE
Flat structure in windows neovim

### ISSUE THREAD

**Issue by sahilsehwag** [el-iot/buffer-tree#1]
I am using neovim on a windows setup. The plugin is showing a flat listing of buffers instead of nested. Every buffer has a separate line with its complete path. Basically no tree is getting generated with multiple levels.

**Comment by el-iot** [comment]
Hmm have you tried turning off compression with  `let g:buffertree_compress=0`? Otherwise would you mind posting the outputs of `:ls` and `:BufferTree` respectively?

**Comment by el-iot** [comment]
I've realised the the compress option was "on" by default, and I've updated it to be "off" by default. Thanks for pointing that out!

**Comment by sahilsehwag** [comment]
The value of compress options is irrelevant for this issue, since all the file paths are showing absolute path for each, therefore tree structure is not generating for files residing in same directory. I am attaching some screenshots, as you can see it seems that its the path separator issue, nix style path "/" are working but "\\" are not.

![Screenshot (35)](https://user-images.githubusercontent.com/10343213/86027777-c2678100-ba4e-11ea-994d-d12ea9a21f8a.png)
![Screenshot (36)](https://user-images.githubusercontent.com/10343213/86027785-c398ae00-ba4e-11ea-8b3d-574b3b7cf93e.png)
![Screenshot (37)](https://user-images.githubusercontent.com/10343213/86027789-c4314480-ba4e-11ea-962b-eadb3221ee91.png)

**Comment by el-iot** [comment]
Ah I see. The best possible option seems to be to make the path-separator configurable (something like
`let g:buffertree_separator="/"`). I'll implement it later. Thanks for pointing this out!

**Comment by el-iot** [comment]
I've updated the plugin so it uses the `g:buffertree_path_sep` as the file-path separator. Do you mind checking to see if changing it to backslash fixes the issue? I had some trouble testing on my machine as nix does not enjoy having backslash characters in file names.

**Comment by sahilsehwag** [comment]
I'll test it out, but besides that I think separator may not be the best solution, the reason being that different vim plugins handle path in different ways, which makes it impossible to work with, if we need to pick one style of path, since the actual path of files in :ls or :buffers will be decided by the plugin command or whatever command that we use to open it. If we observe the second screenshot that I attached has the same problem, 2 file paths with / are working but there's another buffer open(in the same directory) whose path contains \\.
